'use strict';

var constants = {
  LISTEN_RECIPES: 'LISTEN_RECIPES',
  ADD_RECIPE: 'ADD_RECIPE',
  ADD_RECIPE_SUCCESS: 'ADD_RECIPE_SUCCESS',
  ADD_RECIPE_ERROR: 'ADD_RECIPE_ERROR',
  UPDATE_RECIPE_SUCCESS: 'UPDATE_RECIPE_SUCCESS',
  REMOVE_RECIPE_SUCCESS: 'REMOVE_RECIPE_SUCCESS',
  ADD_INGREDIENT: 'ADD_INGREDIENT'
};

module.exports = constants;